### ISSUE TITLE
Gestion de tous/toutes-tout/toute

### ISSUE THREAD

**Issue by YoannLDev** [luffah/JailBreakThePatriarchy-FR#2]
Parfois fonctionne au bon endroit, parfois au mauvais, et inversement, parfois ne fonctionne pas la où ça devrait, et (heureusement), ne fonctionne pas la où ça ne doit pas fonctionner.
- "Toutes" les êtres humaines naissent libres et égaux en dignité et en droits. (OK)
- Chacune _a le_ droit à le gré en "toutes" lieux de sa personnalité juridique. (Pas OK)
- Toute personne accusé d'un acte délictueux est présumé (La ça n'a pas changé, normal ? même si c'est tant mieux.)

**Comment by luffah** [comment]
1) no comment ok
2) il s'agit d'un cas complexe, une résolution simple est de définir "tous lieux" en cas particulier, c'est le coeur du problèmes 
3) "toute" n'est pas présent dans le lexique
-> Solution a : placer 'tout' dans les pronoms et ne pas le changer si le mot suivant ne change pas (en essayant d'exclure les mots de genre neutre...
-> Solution b : lieux -> places

**Comment by luffah** [comment]
Peux tu m'indiquer si tu as modifier le lexique ?

**Comment by YoannLDev** [comment]
Oui j'ai modifié le lexique pour avoir un maximum de mots adaptés aux textes de l'expo, je t'envoie ça dès que j'ai fini.

**Comment by YoannLDev** [comment]
Hum, du coup le lexique la est actuellement très adapté aux textes de l'expo, je ne sais pas si ça ne poserait pas un problème de faire un pull de celui la.

**Comment by luffah** [comment]
le probleme est que tu vas devoir t'adapter à ma solution..
problème résolu je commit (Révision 5).
Redis moi si tu y revois des problèmes.

**Comment by YoannLDev** [comment]
Oui je m'adapte à ta solution, mais pour l'instant il faut surtout que j'adapte aux textes choisis pour l'expo pour avoir le meilleur résultat possible.

**Comment by luffah** [comment]
Pour la définition du lexique (en fait c'est aussi un truc pointu):
Pense à mettre les mots qui pourraient être leur propre équivalent féminin si ces mots posent problèmes.
var correspondance=[
['membres','membres',''],
["les","les",""], ...

A coté de ça, je n'ai pas très bien rempli la table des pronoms qui est utilisée dans l'ordre (donc mettre les groupes de mots en premier - par exemple 'tous les' avant 'tous').
// Définition des pronoms au singulier
var pronoms_singulier  =['un','une','le','la','son','sa','votre','leur',
                          'toute autre','tout autre',
                          'tout le', 'toute la', 'tout un', 'toute une'];
// Définition des pronoms au pluriel
var pronoms_pluriel  =['des','les','ses','vos','leurs','toutes les', 'tous les'];

**Comment by YoannLDev** [comment]
Et ne faudrait-il pas passer la var correspondance avant la var complete ? Pour éviter les conflits, et qu'il prenne en compte les ensembles de mots avant les mots à l'unité.

**Comment by YoannLDev** [comment]
Ok donc on fait comme ça : 
Mon dictionnaire actuel pour la présentation lors de l'exposition, et ta version sera celle que j'enverrais aux visiteurs qui voudraient pouvoir installer l'extension chez eux (ils sont au courant que c'est en cours de développement).
La les PC ne sont pas encore installés dans l'expo, donc je vais rentrer chez moi, j'installe le tout demain.

**Comment by luffah** [comment]
Ca se passe au milieu ?

**Comment by YoannLDev** [comment]
Oui c'est ça. Demain soir 18h pour l'inauguration.
