### ISSUE TITLE
égaux/égales

### ISSUE THREAD

**Issue by YoannLDev** [luffah/JailBreakThePatriarchy-FR#3]
Toutes les êtres humaines naissent libres et égaux en dignité et en droits. Elles sont douées de raison et de conscience et doivent agir les unes envers les autres dans un esprit de fraternité.

Je n'arrive pas à traduire égaux en égales, pourtant je l'ai correctement ajouté à la var complete, j'ai également tenté en la mettant dans la var correspondance.

**Comment by luffah** [comment]
Il s'agit d'un problème avec la cupure des mots '\b', je l'avais résolu pour la fin des mots mais pas le début...

**Comment by YoannLDev** [comment]
Ce n'est pas grave au pire :) Sachant que j'ai ce soucis que pour ce mot la sur l'ensemble des textes pour l'expo, c'est pas trop grave.

**Comment by luffah** [comment]
Gestion de la coupure des mots en début de mot, par contre les é passent en majuscule ...
-> révision 6

**Comment by YoannLDev** [comment]
comment puis-je faire pour télécharger un seul fichier ? Puisqu'au final, il n'y a que le myscript.js que j'ai a télécharger.

**Comment by luffah** [comment]
Faits plutot une copie de ce que tu a changer et prends tout pour remettre tes modifs à partir du fichier du svn. 
Commit tes modifications ensuite.

**Comment by luffah** [comment]
Problème é majuscule corrigé dans la révision 7.
