### ISSUE TITLE
La homme / l'femme

### ISSUE THREAD

**Issue by YoannLDev** [luffah/JailBreakThePatriarchy-FR#5]
http://www.deslettres.fr/lettre-dolympe-de-gouges-a-marie-antoinette-declaration-des-droits-de-la-femme-et-de-la-citoyenne/

Salut !
Quelques soucis sur ce texte, qui ne sont pas présents dans les autres, la femme devient la homme et l'homme devient l'femme ... Egalement pour la citoyenne qui devient la citoyen... Or, je n'ai pas ces soucis dans les autres textes.

**Comment by luffah** [comment]
Ce texte utilise un caractère spécial qui n'est pas l'apostrophe standard mais une apostrophe oblique.

**Comment by YoannLDev** [comment]
Ah ouais, pas chiants les enfants... j'vais voir si j'peux trouver une autre version de ce texte du coup !

**Comment by luffah** [comment]
je vois pour une correction

**Comment by YoannLDev** [comment]
Peux-tu également ajouter les tirets s'il te plait ?
 les hommes seront-"elles" toujours isolés les uns des autres et ne feront-"elles" jamais corps avec la société ?

**Comment by luffah** [comment]
Révision 20.
La solution demande beaucoup de calcul, afin de réussir à propager la casse.

**Comment by YoannLDev** [comment]
Hm, je viens de perdre la translation de "la Patrie" en "la Matrie" avec ton dernier update, or il est toujours dans mon lexique. (Peut-être la majuscule qui gêne ?)
Il y a également un certain nombre de mots inversés qui ne sont plus affichés en gras. comme dans ce texte http://www.un.org/fr/documents/udhr/ l'homme devienne la femme, mais ce n'est pas mis en valeur.
 EDIT : Il n'y a que pour la translation "l'homme" -> "la femme" où ça ne se met pas en gras. L'homme  se met en gras quand il provient de la femme, mais la femme ne se met pas en gras quand l'occurence d'origine est "l'homme".

**Comment by luffah** [comment]
ok, il faut encore pousser l'algorithme donc.
Pour  la transition ("translation" c'est pas français...) de "la Patrie" en "la Matrie", un contournement est de mettre "de la Patrie" "de la Matrie" dans le dico

**Comment by luffah** [comment]
Révision 21 propagée.
Redis moi si la dernière version est mieux, et as tu moyen de faire une liste dans un seul fichier contenant les URL et les fautes qu'on ne veut pas revoir. On appelle ça un cahier de recette. :p

**Comment by YoannLDev** [comment]
En effet c'est mieux, je te ferais une liste au plus vite.
Cependant, as-tu moyen d'upload un fichier .crx à jour, si possible ?
Je viens de finir le tutoriel d'installation en .pdf, mais il est basé sur le fichier .crx qui lui n'est pas à jour.
Merci d'avance :)

**Comment by luffah** [comment]
OK cependant les mots (resources.js) ne sont pas à jours.

**Comment by YoannLDev** [comment]
Ah oui exact. Mais du coup je n'y comprend aux svn, tu m'as envoyé un lien avec 40 000 logiciels, et je ne trouve même pas de lien "télécharger" xD Du coup je ne peux pas t'envoyer le fichier ressources avec les mots à jour... :/

**Comment by luffah** [comment]
-> http://tortoisesvn.net/downloads.html

Ensuite tu fais un "checkout" avec l'URL https://github.com/luffah/JailBreakThePatriarchy-FR

Pour préparer le .crx, c'est la commande "empaqueter l'extension", il faudra selectionner le dossier ".../trunk/JailBreakThePatriarchy-FR" et la clef ".../trunk/JailBreakThePatriarchy-FR.pem".

**Comment by YoannLDev** [comment]
Je t'envoie le fichier sur ton adresse runbox.

**Comment by YoannLDev** [comment]
Heu, en retard ce commentaire;. Je télécharge tortoise et je vois ça :)

**Comment by YoannLDev** [comment]
Ok j'ai réussi ! Mais je ne sais pas comment t'envoyer le fichier ressources, dans tout les cas ^^

**Comment by luffah** [comment]
Au moment de récupérer le dossier, il doit y avoir eu une synchronisation entre l'explorateur Windows et Tortoise. 
Il y a un menu Tortoise qui s'affiche si tu fais un clique-droit sur le dossier, si ce n'ai pas le cas il faut créer un nouveau dossier, et utiliser SVN Chechout (en faisant clique droit ).
http://liris.cnrs.fr/mepp/download/Tutoriel%20TortoiseSVN.pdf
Une fois que tu as modifier le fichier, tu refais clique droit sur le fichier ou le dossier et dans ou à coté du menu Tortoise, tu as SVN Commit, c'est la commande à faire pour envoyer les mises à jour sur le SVN. 
Normalement, on ne "commit" jamais sans avoir tester et expliquer ce que ça change (en l'occurence le message que t'aura à mettre ce sera genre "mise à jour du dictionnaire -> ressource.js".

**Comment by YoannLDev** [comment]
Revision 23 ajoutée avec les mots à jour.

**Comment by YoannLDev** [comment]
Merci pour ce grand apprentissage !

**Comment by luffah** [comment]
Bon je crois que ce problème est clos dans la Révision 24, j'ai aussi anticipé un prochain problème en  ajoutant un support pour que "contre elle" se transforme en "contre lui"...  voir table  'correspondance_sujet' dans 'ressources.js'

**Comment by YoannLDev** [comment]
Tu as bien eu accès au fichier ressources avec tout les mots à jour du coup
? (pour être sûr que ça ait fonctionné)

2015-04-08 22:36 GMT+02:00 luffah notifications@github.com:

**Comment by luffah** [comment]
oui
Utilise l'interface pour parcourir le code pour vérifier.
https://github.com/luffah/JailBreakThePatriarchy-FR/blob/master/JailBreakThePatriarchy-FR/lib/ressources.js
