### ISSUE TITLE
Ajouter le caractère "œ" dans les caractères possibles

### ISSUE THREAD

**Issue by YoannLDev** [luffah/JailBreakThePatriarchy-FR#6]
Tout est  dit dans le titre (sœur, cœur, etc...)

**Comment by luffah** [comment]
c'est fait (dictionnaire à vérifier/mettre à jour) - avant Révision 24

**Comment by YoannLDev** [comment]
Qu'entends-tu par "mot à vérifier" ? Car tu n'as pas fait d'update du
fichier ^^
si tu veux tester avec le mot "soeur" (en caractère attaché, déjà présent
dans ressources.js), c'est le 3eme mot du préambule ici
http://www.deslettres.fr/lettre-dolympe-de-gouges-a-marie-antoinette-declaration-des-droits-de-la-femme-et-de-la-citoyenne/

**Comment by YoannLDev** [comment]
Peux-tu également m'expliquer la syntaxe pour correspondance_singulier et
correspondance_pluriel s'il te plait ?
ça c'est le code d'origine :
var correspondance_singulier=[
["fils","fille"]
]
var correspondance_pluriel=[
["fils","filles"]
]

Je me suis dit que ça allait être le même format que var correspondance,
mais non, j'ai tenté ça et ça a tout planté
var correspondance_singulier=[
["courageux","courageuse"],
["crapuleux","crapuleuse"],
["crasseux":"crasseuse"],
["fils","fille"]
]
var correspondance_pluriel=[
["courageux","courageuses"],
["crapuleux","crapuleuses"],
["crasseux","crasseuses"],
["fils","filles"]
]

**Comment by YoannLDev** [comment]
Ok ! Oublie mon dernier mail, j'ai fait une erreur de syntaxe sur crasseux,
je n'avais pas vu ^^

**Comment by YoannLDev** [comment]
Commit 29 - MàJ du fichier ressources.js
Commit 30 - MàJ du fichier de test validation.xls

**Comment by YoannLDev** [comment]
<Commentaire hors sujet> C'est la partie liste des personnes / Liste des événements que tu as ajouté
dans le readme ? Ou y a t'il autre chose que je dois relire ?

**Comment by luffah** [comment]
< Réponse au commentaire hors sujet >  Il s'agissait juste de te laisser la possibilité de réagir si tu n'est pas en phase avec le README

**Comment by luffah** [comment]
J'ajouterai pour le "oe" un truc spécial qui le transforme en 'œ' car c'est pénible à écrire, et par consequent la faute de frappe doit être ultra-récurente

**Comment by YoannLDev** [comment]
Ok mais il faut que ça fonctionne aussi pour les mots qui n'ont pas la
faute de frappe :)

Je viens de trouver un article de novembre 2000 sur la féminisation des
fonctions, je suis en train de contacter des bibliothécaires pour tenter de
me le procurer. Ça ajouterai pas mal de mots dans le lexiques qui ne sont
pas encore communs mais qui ont déjà été pensés.
