### ISSUE TITLE
Liste des erreurs rencontrées

### ISSUE THREAD

**Issue by YoannLDev** [luffah/JailBreakThePatriarchy-FR#7]
Je te fais une liste ici, ce sera plus simple que de balancer 40 000 erreurs d'un coup.

http://www.un.org/fr/documents/udhr/
"dans la dignité et la valeur de la personne humaine, dans l'égalité des droits des hommes et des hommes,"
(5ème paragraphe, 3ème ligne)
-> "des femmes" est bien modifié (2ème position), mais le premier "des hommes" reste ainsi sans être inversé.

"Tous les êtres humaines naissent libres et égales en dignité et en droits."
(Article premier, première phrase)
-> Dans ressources.js : Ligne 2099 : 'tous': 'toutes', 'toutes': 'tous',  or "Tous" n'est pas modifié en "Toutes".

**Comment by luffah** [comment]
Ce serait mieux d'avoir quelque chose qui ressemble à un cahier de recette et qui serve de référence à chaque modification :
http://phortail.org/webntic/Cahier-de-recette.html

Cela sert à garder tous les cas problématique/fonctionnalité de coté, et à les revérifier à chaque fois (tests de non-régression).
Je te met la première version dans le répertoire principal (d'ici 5 minutes).

Il n'est pas utile de metre dedans le contenu du code. Il s'agit du point de vue utilisateur uniquement.

## Genre un feuille excel comme ci-dessous :

| URL de la page | Paragraphe | Ligne | Mots d'origine | Substitution souhaité | Date du test | Conforme | Commentaire |
| :-- | :-- | :-- | :-- | :-- | :-- | :-- | :-- |
| http://www.un.org/fr/documents/udhr/ | 1 | 1 | "Tous" | "<strong>Toutes</strong>" | 09/04/2015 | Non |  |
| http://www.un.org/fr/documents/udhr/ | 5 | 3 | "des hommes" | "<strong>des femmes</strong>" | 09/04/2015 | Non |  |
| http://www.un.org/fr/documents/udhr/ | 5 | 3 | "des femmes" | "<strong>des hommes</strong>" | 09/04/2015 | Oui |  |

**Comment by luffah** [comment]
Ajout validation.xls au svn
-> pour ouvrir le fichier téléchargé, tu peux utiliser  Libre Office Calc, ou Gnumeric ou Google spreadsheet  ou Microsoft Excel
