### ISSUE TITLE
SyntaxError & Reference Error

### ISSUE THREAD

**Issue by YoannLDev** [luffah/JailBreakThePatriarchy-FR#8]
ressources.js:17 Uncaught SyntaxError: Unexpected token <<
myscript.js:38 Uncaught ReferenceError: wbindset is not defined

Il y a 2 erreurs dans le code. Plus rien ne fonctionne ^^ Je te laisse gérer ça, je continue à m'occuper du dictionnaire

**Comment by luffah** [comment]
L'erreur de myscript.js
découlle de la celle dans ressources.js.
As tu fait une modif dedans ? je n'ai pas d'erreur de mon coté

**Comment by YoannLDev** [comment]
Non je n'ai fait aucune modif, a part ajouter des mots dans le lexique :/

**Comment by luffah** [comment]
ligne 17 normalement c'est un ligne blanche entre des commentaires... peux tu regarder si tu n'a pas ajouter des trucs par erreur ? si tu vois rien fais un commit et je regarderai l'erreur.
Le truc c'est quand général ce genre d'erreur est assez simple à résoudre. tu va à la ligne indiquée par les logs et tu corrige (en rajoutant des parenthèses, un point virgule, etc... c'est le sens de problème de syntaxe )

**Comment by YoannLDev** [comment]
ligne 17 & 2483 : <<<<<<< .mine
ligne 73 & 2505 : =======
ligne 129 & 2529 : >>>>>>> .r31

C'est justement ce que j'ai pas compris quand j'ai fait l'update de mon
fichier ...

**Comment by YoannLDev** [comment]
Bon bah j'ai supprimé ces lignes, et ça fonctionne à nouveau. J'ai rien
compris sur ce coup la. Je fais un commit du fichier ressources.js pour que
la version en ligne soit propre et fonctionnelle

**Comment by YoannLDev** [comment]
https://chrome.google.com/webstore/detail/au-revoir-patrie/nfehkehmpfafebpkmoidphlbbgcgfcje?hl=fr

La version actuelle et fonctionnelle est disponible en ligne.

**Comment by luffah** [comment]
OK. les <<<< que tu as vu semble être un indicateur de changement d'une version à une autre. Normalement SVN previent avant de mettre ces trucs là. Je nettoie le truc.

**Comment by YoannLDev** [comment]
Salut.

Qu'entends-tu par "Ajout possibilité infobulles" ?

2015-04-16 21:06 GMT+02:00 luffah notifications@github.com:

**Comment by luffah** [comment]
Salut !

En fait, j'ai ajouté la possibilité d'utiliser le mot ancien $1 et le nouveau $2 dans les options de la balise HTML du mot changé. 
Dans la configuration que j'ai mis par défaut, si tu passe ton curseur au dessus du mot changé (en gras donc) tu verra apparaître l'ancien mot dans un petit cadre.

Voilà.

Tchou

**Comment by YoannLDev** [comment]
Ahhh oui, bien pensé ça !! Bien joué :)

**Comment by YoannLDev** [comment]
Il y a un problème étrange, lorsque je lance l'extension en mode
développeur, l'ajout des "title" fonctionne parfaitement.

Par contre, quand je balance l'extension sur le Chrome Web Store pour la
télécharger en ligne directement, les titles ne sont pas activés... Or ce
sont exactement les mêmes fichiers que j'u

**Comment by YoannLDev** [comment]
erreur d'envoi.

Ce sont les mêmes fichiers que j'utilise dans les 2 cas puisque j'utilise
le dossier JailBreak dans le trunk.
